services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    # "ports" section is REMOVED because we are using host network
    network_mode: host
    environment:
      TZ: 'Asia/Amman'
      FTLCONF_webserver_api_password: ${ADMIN_PASSWORD}
      # This forces the internal web server to listen on 8050 directly
      FTLCONF_webserver_port: 8050 
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d