services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8085:80"
    environment:
      TZ: 'Asia/Amman'
      FTLCONF_webserver_api_password: ${ADMIN_PASSWORD}
      FTLCONF_misc_dnsmasq_lines: ${DNSMASK_LINES}
    volumes:
      - ./etc-pihole:/etc/pihole
